### ISSUE TITLE
Expected a value of type 'int', but got one of type 'double' flutter web

### ISSUE THREAD

**Issue by RahulAlchemy** [MixinNetwork/libsignal_protocol_dart#42]
I'm trying integrate Signal protocol in flutter web .

I get this error
  `Expected a value of type 'int', but got one of type 'double'`

When i call this method
 //3.0.0 nullsafety  version
 `KeyHelper.generateSignedPreKey(identityKeyPair, signedPreKeyId);`

//0.5.3 version
`generateSignedPreKey(identityKeyPair, signedPreKeyId);`

on both version I get same issue.

I was able to trace the issue. Issue is in `edwards25519.dart`.

**Comment by Tougee** [comment]
Some libraries we use in this code base are incompatible with dart2js, so we made some modifications to this workaround, but we can't merge them into the main branch because the changes lack performance.

You can use this library for the Flutter web app as shown below for now, until we find a better way to do it.
``` yaml
libsignal_protocol_dart:
    git:
      url: git@github.com:MixinNetwork/libsignal_protocol_dart.git
      ref: web
```
